perception_node:
  ros__parameters:
    cloud_topic: "/points"
    world_frame: "map"
    camera_frame: "laser_data_frame"

    # Size of the x,y,z leaf for the voxel grid filter in meters
    voxel_leaf_size: 0.2

    # Max number of ransac iterations
    plane_max_iterations: 120
    # Ransac dist thresh in meters
    plane_distance_threshold: 0.35

    # Min and Max number of points for euclidean clustering
    cluster_min_size: 2
    cluster_max_size: 2000
    cluster_tol: 1.35